services:
  tasker:
    image: dev_tasker
    container_name: dev-tasker
    env_file:
      - .env
    ports:
      - "3030:3030"
    networks:
      - forge_highway
  redis:
    image: "redis:latest"
    container_name: dev-redis
    ports:
      - "6379:6379"
    networks:
      - forge_highway

networks:
  forge_highway:
    external: true